#!/usr/bin/env bash
# Bootstraps a local dev stack for telegrind:
#   - .env                 (dev defaults; secrets left blank for you to fill)
#   - compose.override.yml (local-only tweaks, auto-merged by `docker compose`)
# Both are gitignored. Existing files are never overwritten — safe to re-run.
set -euo pipefail
cd "$(dirname "$0")"

created=0

if [ -e .env ]; then
  echo "= .env already exists — leaving it untouched"
else
  cat > .env <<'EOF'
# Local dev config (gitignored). Generated by dev-setup.sh.

# --- infra: safe local defaults ---
POSTGRES_PASSWORD=postgres
# The host reaches postgres on localhost:5433; the bot container reaches it
# by service name, which compose.yml sets for that service.
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5433/postgres

# --- secrets: fill these in before `docker compose up` ---
BOT_TOKEN=
ANTHROPIC_API_KEY=
EOF
  echo "+ wrote .env (fill in BOT_TOKEN / ANTHROPIC_API_KEY before starting)"
  created=1
fi

if [ -e compose.override.yml ]; then
  echo "= compose.override.yml already exists — leaving it untouched"
else
  cat > compose.override.yml <<'EOF'
# Local dev overrides (gitignored). Auto-merged on top of compose.yml.
# Generated by dev-setup.sh. Edit freely — it's yours, not committed.
services:
  postgres:
    # Don't restart-loop: a crash stays down so its logs are visible.
    restart: "no"
  bot:
    restart: "no"
EOF
  echo "+ wrote compose.override.yml"
  created=1
fi

echo
if [ "$created" -eq 1 ]; then
  echo "Done. Next: edit .env, then \`docker compose up\`."
else
  echo "Nothing to do — dev files already present."
fi
