"""message and fact

Revision ID: f8ba900863f4
Revises: 2700e0b3a8b6
Create Date: 2026-09-09 13:41:40.909596

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8ba900863f4"
down_revision: str | Sequence[str] | None = "2700e0b3a8b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_pk", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("transcript", sa.String(), nullable=True),
        sa.Column("transcript_model", sa.String(), nullable=True),
        sa.Column("audio_file_id", sa.String(), nullable=True),
        sa.Column("audio_duration", sa.Integer(), nullable=True),
        sa.Column("tg_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_pk"], ["chat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chat_pk", "message_id", name="uq_message_chat_pk_message_id"
        ),
    )
    op.create_table(
        "fact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_pk", sa.Integer(), nullable=False),
        sa.Column("message_pk", sa.Integer(), nullable=True),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("worksheet", sa.String(), nullable=False),
        sa.Column("sheet_key", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["chat_pk"], ["chat.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_pk"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chat_pk", "worksheet", "sheet_key", name="uq_fact_chat_pk_worksheet_key"
        ),
        sa.UniqueConstraint("message_pk", "seq", name="uq_fact_message_pk_seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact")
    op.drop_table("message")
    # ### end Alembic commands ###
