"""unique chat_id

Revision ID: 2700e0b3a8b6
Revises: 1d25990ec8c1
Create Date: 2026-04-24 01:57:53.760456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2700e0b3a8b6'
down_revision: Union[str, Sequence[str], None] = '1d25990ec8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chat_chat_id', 'chat', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_chat_id', 'chat', type_='unique')
    # ### end Alembic commands ###
